[package]
name = "USDTRepo"
version = "0.1.0"

[addresses]
UsdtIssuer = "0x70f7070b07046c4eb6d0288a77c9dd8f829e09d797b8492e343dd360324ffe0b"
move_std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
aptos_token = "0x3"

[dependencies]
#StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "01c84198819310620f2417413c3c800df8292ae5" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "02e41b3eb12df24103412630d20d72db8bcca2ed", subdir = "aptos-move/framework/aptos-framework"}
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "02e41b3eb12df24103412630d20d72db8bcca2ed", subdir = "aptos-move/framework/aptos-stdlib"}
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "02e41b3eb12df24103412630d20d72db8bcca2ed", subdir = "aptos-move/framework/move-stdlib"}
