[package]
name = "Starswap-Core"
version = "2.0.6"

[addresses]
StarcoinFramework = "0x1"
SwapAdmin = "0x8c109349c6bd91411d6bc962e080c4a3"
SwapFeeAdmin = "0x9572abb16f9d9e9b009cc1751727129e"
BuyBackAccount = "0xa1869437e19a33eba1b7277218af539c"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "345a3900a0064dc57a9560235bc72c12f03448b1" }
Poly-STC-Bridge = { git = "https://github.com/Elements-Studio/poly-stc-contracts.git", rev = "eb538376a3a0c619dc6b6e0a0262af5face95b30" }
Mock-Token = {local = "./MockToken"}