[package]
name = "Starswap"
version = "0.9.0"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin.git", subdir="vm/stdlib", rev="3e895169a8f8dd883277050bb90645c52a370cee"}
